Added check for existing screen session.

diff --git a/deploy/bin/start_screen b/deploy/bin/start_screen
--- a/deploy/bin/start_screen
+++ b/deploy/bin/start_screen
@@ -27,12 +27,21 @@ region_names="s01 s02 s03 s04 s05 s06 s07 s08 s09 s10"
 regions=($region_names)
 num_regions=${#regions[*]}
 
-screen -d -m -S OpenSim
+retval=`screen -ls | grep OpenSim`
+if [ -n "${retval}" ]
+then
+    echo
+    echo "ERROR: There appears to be an OpenSim screen session running already."
+    echo
+    exit 1
+else
+    screen -d -m -S OpenSim
 
-i=1
-while [ ${i} -le ${num_regions} ]
-do
-    let j=${i}-1
-    screen -X -S OpenSim screen -t ${regions[${j}]} ${i}
-    let i=${i}+1
-done
+    i=1
+    while [ ${i} -le ${num_regions} ]
+    do
+        let j=${i}-1
+        screen -X -S OpenSim screen -t ${regions[${j}]} ${i}
+        let i=${i}+1
+    done
+fi
